spring:
  application:
    name: ch_coding_app

  datasource:
    url: jdbc:h2:mem:ch_coding_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      path: /h2-console
      enabled: true

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: yeait24@gmail.com
    password: glqzdxevtufuwxfw
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true
        debug: false
    protocol: smtp

springdoc:
  swagger-ui:
    path: /api/doc